#!/bin/bash

## Files and cmd
CONFIG_PATH="$HOME/repos/dotfiles/eww-widgets/eww/bar"
FILE="$HOME/.cache/eww_launch.xyz"
EWW_PATH=$(which eww)
EWW="$EWW_PATH -c $CONFIG_PATH"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many \
         bar
        
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww && echo "running"
else
	${EWW} close-all && pkill eww
	rm "$FILE"
fi
